export const FETCH_LOGIN_LINK_REQUEST = 'FETCH_LOGIN_LINK_REQUEST';
export const FETCH_LOGIN_LINK_SUCCESS = 'FETCH_LOGIN_LINK_SUCCESS';
export const FETCH_LOGIN_LINK_ERROR = 'FETCH_LOGIN_LINK_ERROR';
export const FETCH_SETUP_ACCOUNT_REQUEST = 'FETCH_SETUP_ACCOUNT_REQUEST';
export const FETCH_SETUP_ACCOUNT_SUCCESS = 'FETCH_SETUP_ACCOUNT_SUCCESS';
export const FETCH_SETUP_ACCOUNT_ERROR = 'FETCH_SETUP_ACCOUNT_ERROR';
export const API_ROUTE = `${process.env.REACT_APP_API_HOST}/setup/`;